apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend-config.yaml
  - backend-services.yaml
  - frontend-apps.yaml
  - frontend-gateway.yaml
  - ingress.yaml
