server {
  listen 80;
  server_name _;

  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Proto $scheme;

  location = /auth {
    return 308 /auth/;
  }

  location = /orders {
    return 308 /orders/;
  }

  location = /pay {
    return 308 /pay/;
  }

  location = /wallet {
    return 308 /wallet/;
  }

  location = /activity {
    return 308 /activity/;
  }

  location /auth/ {
    proxy_pass http://auth_app:3001/auth/;
  }

  location /orders/ {
    proxy_pass http://orders_app:3002/orders/;
  }

  location /pay/ {
    proxy_pass http://payments_app:3003/pay/;
  }

  location /wallet/ {
    proxy_pass http://wallet_app:3004/wallet/;
  }

  location /activity/ {
    proxy_pass http://activity_app:3005/activity/;
  }

  location /api/ {
    proxy_pass http://api_gateway:5000/api/;
  }

  location / {
    proxy_pass http://shell_app:3000/;
  }
}
